### ISSUE TITLE
Allow to submit form parameters as "URL encoded"

### ISSUE THREAD

**Issue by gunnarmorling** [unpoly/unpoly#107]
When adding `up-target="..."` to a form, UnPoly will POST it with content type "multipart/form-data", also if `enctype="application/x-www-form-urlencoded"` is declared on the form.

**Comment by triskweline** [comment]
We're using `multiplart/form-data` since that allows us to transfer all kinds of form values, even binary blobs.

Our server-side web framework (Rails) unpacks request params into the same format regardless of the `[enctype]`. I thought that other frameworks would handle this similarily. Does your web application rely on a particular encoding type?

**Comment by gunnarmorling** [comment]
I'm using Java's JAX-RS (via its implementation RESTEasy) and indeed methods receiving URL-encoded forms looks different from ones receiving multipart forms. In any case, wouldn't it be more in the spririt of the standard to use the content type specified for the form?

**Comment by OLibutzki** [comment]
I stumbled upon the same issue. Our backend behaves differently for `multipart/form-data` and `application/x-www-form-urlencoded`. In my opinion unploy would strengthen its non-invasive nature by respecting the form's enctype.

**Comment by OLibutzki** [comment]
Are there any chances that unpoly uses the form's enctype? Unfortunately I'm not familiar with CoffeeScript, so I fear I'm not able to contribute.

**Comment by triskweline** [comment]
This is fixed in [Unpoly 2](https://unpoly.com/changes/2.0.0), which was released today.
