### ISSUE TITLE
Body classes disappearing

### ISSUE THREAD

**Issue by adam12** [unpoly/unpoly#14]
Hello,

I've noticed that classes applied to `body` disappear when using an `up-follow` attribute on a link. I've confirmed they are in the response from the server during the request.

Looking through the code, it sounds like swapping actual `body` elements can be problematic, and my guess is coping the existing attributes from the old `body` element to new element is just as problematic.

Any thoughts?

(Up log attached)

![machines 2017-03-14 12-25-00](https://cloud.githubusercontent.com/assets/17083/23910842/5d13c5d6-08b1-11e7-8109-a1311501a94b.png)

**Comment by adam12** [comment]
I solved it (albeit hackish) with the following diff. It would probably make more sense to copy the `class` attr off of the new `body` from the XHR request, but I wasn't sure where I could gain access to it.

```diff
diff --git a/lib/assets/javascripts/unpoly/dom.coffee b/lib/assets/javascripts/unpoly/dom.coffee
index c3fcb81..9f7ab78 100644
--- a/lib/assets/javascripts/unpoly/dom.coffee
+++ b/lib/assets/javascripts/unpoly/dom.coffee
@@ -507,6 +507,7 @@ up.dom = (($) ->

   # This is a separate method so we can mock it in specs
   swapBody = ($oldBody, $newBody) ->
+    $newBody.attr('class', $oldBody.attr('class')).removeClass('up-destroying')
     $oldBody.replaceWith($newBody)

   transferKeepableElements = ($old, $new, options) ->
```

**Comment by triskweline** [comment]
We should not try to keep attributes from the old `<body>`, this would be inconsistent with how fragment replacement works anywhere else. Instead the attributes from the new `<body>` in the response should be used.

I think the bug is here:
https://github.com/unpoly/unpoly/blob/49baaacb82539fcae63649d0eb177c32e7d7a277/lib/assets/javascripts/unpoly/util.coffee#L202

This is code that parses full HTML pages from the response. jQuery can make a DOM from most strings, but not strings that contain `<html>` or `<body>` tags.

We could fix that code. Or maybe drop IE9 support and use [`DOMParser`](https://developer.mozilla.org/de/docs/Web/API/DOMParser).

**Comment by triskweline** [comment]
Fixed in `0.35.0`.

**Comment by adam12** [comment]
Works :) Thanks!

(I had to build from master as I noticed dist/ was out of date, as well as CDN, just FYI)

**Comment by triskweline** [comment]
Oops, forgot to update dist/, CDN and npm. Did that now. Thanks for the hint!
