### ISSUE TITLE
Compile errors on coffeescript v 2.5.1

### ISSUE THREAD

**Issue by boxxxie** [unpoly/unpoly#149]
maybe not a high priority to support 2.5.#, but i was able to get master to compile only changing 1 line of code (in a different file, i think `session.coffee`)
```
coffee -c .
/unpoly/lib/assets/javascripts/unpoly/classes/change/change.coffee:5:17: error: Can't use @params in derived class constructors without calling super
  constructor: (@options) ->
                ^^^^^^^^
```

**Comment by adam12** [comment]
Supporting 2.5.1 might require some considerable re-tooling. I noticed a Typescript experiment in one of the commits so I wouldn't want to jump the gun on re-tooling for the new Coffeescript yet in case Henning has other plans.

I haven't kept pace with Coffeescript development but it seems at one point it switched to NPM for distribution. The two recommended Ruby gems [coffee-script](https://rubygems.org/gems/coffee-script) and [coffee-script-source](https://rubygems.org/gems/coffee-script-source) haven't kept pace with the Coffeescript releases, so further investigation would be needed.

**Comment by triskweline** [comment]
The next major change after the 2.0 release will be to offer an ES6 build for modern browsers. This will involve changing the build pipeline from Sprockets to Webpack and also use CoffeeScript 2 (which emits ES6 instead of ES5).

A working PoC with Webpack and CoffeeScript 2 is already working in the `hk/webpack` branch, so I'm closing this issue.

> I noticed a Typescript experiment in one of the commits so I wouldn't want to jump the gun on re-tooling for the new Coffeescript yet in case Henning has other plans.

Once we're building with Webpack we will gradually convert packages from CoffeeScript to TypeScript to complement the test suite and produce smaller builds.
