### ISSUE TITLE
List of all Events, Any Request Event, Before Rendering, Loading Mode

### ISSUE THREAD

**Issue by onur-km** [unpoly/unpoly#155]
## List of all Events
Can a special page be prepared for a list of all events belonging to the framework?

## Any Request Event
It must be a comprehensive event that will fire whenever any request (replace, target, follow, submit, etc.) happens. Ex. `up:any-request`! 
Actually, `up:visit or up:request` is great for this, but it can be confusing since there is a special function called `up.visit() and up.request()`.

## Before Rendering
An event must occur at the end of any event (replace, target, follow, submit, etc.), just before the page is rebuilt. Ex. `up: before-render`.

## Loading Mode
A class such as ".loading" must be added to the "html or body" element after a certain period of time after any request (replace, target, follow, submit, etc.) to inform users that the process is being executed.

So we can stop or complete the animation or effect using the `up: before-render` event above.

**Comment by adam12** [comment]
> List of all Events

Worth waiting for 2.0 since there's a bunch of changes architecturally. The documentation for the site is generated from the source code, so the parser might have to be adjusted to make the page to list everything.

Do you find the current site searching for `up:` insufficient for finding events?

> Any Request Event

Probably should wait and see what 2.0 brings.

> Before Rendering

I think this is fixed in 2.0.

> Loading Mode

I think you could probably get this now by using the `up:proxy:load` and `up:proxy:loaded` events. Have you tried it?

**Comment by onur-km** [comment]
@adam12 

This is very good. I'm looking forward to v2.

Yes, all the events are a little difficult to find. Actually I couldn't see the proxy 'with `load` and `loaded` events. This will make my job a little easier. **The project is very good.**

**Comment by triskweline** [comment]
What are you trying to accomplish?

If you want to show loading indicators while requests are pending, take a look at the [`up:proxy:slow`](https://unpoly.com/up:proxy:slow) event.

Closing this as it doesn't look like we're making a change here.
