### ISSUE TITLE
Update history after up.submit() with POST

### ISSUE THREAD

**Issue by perifer** [unpoly/unpoly#17]
I can't get the browser history to update after `up.submit()` with POST.

> [options.history=true] 
Successful form submissions will add a history entry and change the browser's location bar if the form either uses the GET method or the response redirected to another page **(this requires the unpoly-rails gem)**. If you want to prevent history changes in any case, set this to false. If you pass a String, it is used as the URL for the browser history.

I'm not using the unpoly-rails gem, but reading http://unpoly.com/up.protocol#redirect-detection it seems it should be possible to do this by simply responding with a header: `X-Up-Location: /current-url`.

Looking through the source code it seems that only GET-requests are supported (I might be looking at the wrong place though): https://github.com/unpoly/unpoly/blob/master/lib/assets/javascripts/unpoly/dom.coffee#L282

**Comment by triskweline** [comment]
Unpoly will only update history if the response of a form submission is a `GET` request. Otherwise we would update the browser location with a URL that the user cannot reload.

1. Redirect to a `GET` page in the server-side code that processes the form. This is what we do.
2. Pass the new URL as a string as `{ history }` option, it will override the default behavior.
3. Have the server-side code that processes the form set two headers with the new URL:
   ```
   X-Up-Method: GET
   X-Up-Location: /new-url
   ```

**Comment by perifer** [comment]
Thanks. `X-Up-Method: GET` was probably what I was missing, haven't seen it in any documentation from what I remember.
