### ISSUE TITLE
Disqus comments system don't work with Unpoly

### ISSUE THREAD

**Issue by alnuaimi94** [unpoly/unpoly#170]
Currently I'm building a blog using Django and Unpoly, I'm using the [Disqus](https://disqus.com/) comments system
on the detail article page.

**The problem** is that the comments system **does not appear until I make a forced reload of the page**.

Are there suggestions or instructions regarding that?
 
**Notice:**
I also used the **Facebook comment system** and the same problem occurred

I use this link to access detail article page:
```html
<a href="{{ article.get_absolute_url }}" up-cache="false" up-follow>link</a>
```

**Comment by adam12** [comment]
How are you loading Disqus? Do you control where it is rendered?

Simply adding `up-keep` to the container element for the Disqus widget might help.

**Comment by alnuaimi94** [comment]
> How are you loading Disqus? Do you control where it is rendered?
> 
> Simply adding `up-keep` to the container element for the Disqus widget might help.

I am sorry for the delay in replying because I rebuilt the project from scratch, I used **up-keep** and it didn't work. This is the link to the project https://github.com/alnuaimi94/Personal-Website if you want help me. 

Thank you again.

**Comment by adam12** [comment]
I'd use an `up.compiler` based on a custom attribute.

ie.

```html
<article disqus-identifier="{{ post.id }}">
  render your post here
</article>
```


```javascript
up.compiler("[disqus-identifier]", async function(el) {
  const identifier = el.getAttribute("disqus-identifer")
  await loadScript("https://codex-5.disqus.com/embed.js")
  
  DISQUS.reset({
    reload: true,
    config: function () {
      this.page.identifier = identifier
      this.page.url = window.location.href
    } 
  })
})
```

with `loadScript` coming from [here](https://makandracards.com/makandra/52361-unpoly-loading-large-libraries-on-demand) and the API for Disqus [here](https://help.disqus.com/en/articles/1717163-using-disqus-on-ajax-sites).

I didn't test this but I'm sure you can use it as a starting point.

I'm going to close this since it's not necessarily an issue with Unpoly. If you're still unable to get this working, I suggest posting to the [mailing list](https://groups.google.com/g/unpoly) which generally has more viewers to these discussions, and who may be able to help guide you.
