### ISSUE TITLE
Images with a `srcset` attribute do not show up or are blurry in Safari

### ISSUE THREAD

**Issue by angelikatyborska** [unpoly/unpoly#175]
I work on a project that uses Unpoly links to navigate between pages. Recently we improved one of the pages by adding `srcset` and `sizes` attributes to images so that they get downloaded with appropriate sizes and still look good on big screens.

This has lead to bug reports from a few macOS Safari users. Some of the reports were saying that those images do not show up at all (but only after using Unpoly to reload a page fragment, they always show up on initial page load), and others were saying that the images do show up, but always load using the smallest possible size from `srcset` and thus are very blurry.

## How to reproduce

I created a repository with a minimal project (two HTML files). In that project, I can reliably reproduce in my Safari (macOS Big Sur 11.4, Safari Version 14.1.1 (16611.2.7.1.4)) that the images do not appear at all.

https://github.com/angelikatyborska/unpoly_img_test/

## Workaround?

By trying anything that comes to mind, I discovered that this code can be added to "fix" the problem:
```
up.compiler('img[srcset]', function (el) {
  const srcset = el.getAttribute('srcset')
  el.setAttribute('srcset', srcset)
})
```

However, that seems a bit hacky. I'm not sure what consequences this can have.

Is there a better way to handle this problem? I am assuming it's a bug in Safari, but maybe there's something that Unpoly can change to fix the problem?

**Comment by triskweline** [comment]
Wow @angelikatyborska, that must be the best prepared issue I've ever received :smile: Thanks for the detailed report and reproduction repo.

I believe what happens is this:

- When Unpoly receives a HTML response from the server it uses [`DOMParser`](https://developer.mozilla.org/en-US/docs/Web/API/DOMParser) to parse it into a separate element tree. This tree is used to match elements between the `document` and the response. If a match is found, the matching element is moved from the response tree to the `document`.
- Since the element in the response tree is not visible, Safari does not render any contained images and assigns a width and height of zero.
- When the image is moved to the `document`, Safari needs to reconsider the image size, but has a bug where it does not.

This seems to be a long-standing bug in Webkit:

- https://dev.to/ben/safaris-implementation-of-srcset-is-buggy-rendering-the-whole-feature-basically-useless-8d
- https://stackoverflow.com/questions/45487105/ajax-loaded-images-in-safari-not-respecting-srcset
- https://bugs.webkit.org/show_bug.cgi?id=215375

> Is there a better way to handle this problem?

Some people have reported that a `<picture>` with multiple `<source>` children does not exhibit the issue.

> However, that seems a bit hacky. I'm not sure what consequences this can have.

It looks harmless enough. Maybe check if an unaffected browser (like Chrome) does not make duplicate requests for the same image.

> maybe there's something that Unpoly can change to fix the problem?

I can confirm that this also happens for the V2 release candidate.

I'm not sure what Unpoly can do to handle this better. Aside from including the hack above in the library, which I don't love.

I'm leaving this issue open for a while in case someone else has a better idea.

**Comment by angelikatyborska** [comment]
Thank you for the response 🙂. We'll try the workaround then. It doesn't look like it's causing any duplicate requests.

**Comment by ionurboz** [comment]
@angelikatyborska good catch. Excuse me, I'm cloning the repository so as not to say what was this error in the future.

**Comment by adam12** [comment]
I believe this has been corrected on recent versions of Safari. I put together a [Glitch here](https://glitch.com/edit/#!/ultra-fascinated-texture?path=index.html%3A15%3A34) from the example Github repo above and cannot reproduce it.

Safari Version 16.5 (18615.2.9.11.4)
