### ISSUE TITLE
Update nearest target to origin

### ISSUE THREAD

**Issue by sprql** [unpoly/unpoly#19]
Hello, 

I have the page with several sections and forms:

```html
  <div class="section">
    <form up-target=".section"></form>
  </div>

  <div class="section">
    <form up-target=".section"></form>
  </div>
```

A form request returns one section only, not section list.
I've noticed, that when I submit the second form and get updated second list it will replace the first section on the page, and the old section remains unchanged.

What do you think about it?

**Comment by triskweline** [comment]
Unpoly always needs a unique `id`, `class` or `up-id` attribute to match elements from the response with elements from the current page.

Unfortunately we cannot be smarter about this, since the concept of "nearest" is really hard to resolve when we also allow servers to respond with partial responses.

In case your sections don't have a unique attribute, but your forms do, you can do this:

```
  <div class="section">
    <form id="form1" up-target=".section:has(&)"></form>
  </div>

  <div class="section">
    <form id="form2" up-target=".section:has(&)"></form>
  </div>
```

**Comment by sprql** [comment]
It's clear to me now how to properly use unpoly for this situation and I got a working solution.

Thank you!

**Comment by triskweline** [comment]
You're welcome :)
