### ISSUE TITLE
dist folder in tag v2.0.1 doesn't contain js/css files

### ISSUE THREAD

**Issue by boxxxie** [unpoly/unpoly#193]
### Bug description

dist folder in tag v2.0.1 doesn't contain js/css files

### Steps to reproduce the behavior:

`git checkout v2.0.1`

### Expected behavior

expect dist folder to have compiled js and css files

--------

what's the point of a dist folder if it doesn't contain the compiled files?

**Comment by adam12** [comment]
It's [intentional](https://github.com/unpoly/unpoly/commit/64bc03656bac8d58a04688b09989b2f058a425a9).

Maybe `dist` would be more appropriate named as `dist-skeleton`, now that it's only the base structure for packaging.

I'm not sure the reasoning, but I've noticed that when developing Unpoly locally, the `dist` tree is always dirty when building. Which makes sense, but can be annoying during development. Maybe Henning can provide more insight if he has the opportunity.

**Comment by boxxxie** [comment]
you could have a release branch, and make the tags from that.

i actually don't understand what you mean by `dirty`... are you not deleting previous build files on build?

removing the dist from git altogether seems extreme, and atypical of frontend projects. i think there is a convenient compromise.

**Comment by triskweline** [comment]
People kept making PRs on the build files instead of the sources. Also the `dist` folder was always outdated. Every build made the repo 500 KB bigger with every build.

Right now if someone needs the build files and cannot use a package manager they need to download it from the [CDN](https://unpoly.com/install/cdn).

If we want to bring back direct download we could:

- Offer direct Download Links `([rel=download])` to the CDN files on Unpoly.com
- Update the build script in the `Rakefile` so it produces a GitHub release that includes the build (via GraphQL API)

**Comment by triskweline** [comment]
I added docs for downloading static files here: https://unpoly.com/install/download

The `dist` folder is not coming back for reasons explained above, so I'm closing this issue.
