### ISSUE TITLE
Support for IE 9

### ISSUE THREAD

**Issue by deepakmn** [unpoly/unpoly#23]
I'm loving unpoly. I'm primarily a server side developer and unpoly has brought back to me the joy of web programming. Now I can use any of the open source css libraries to build beautiful and functional UIs without having to wrap my head around all the new <insert_cool_js> libraries. I understand that unpoly does not boot for IE9 and below and I may have to fall back to jquery to init jquery plugins. Would I have to maintain two binding files for all jquery plugins I use - one with unpoly binding and another with standard jquery binding to initialize components or is there a way to achieve this in a single file as a fallback ? I apologize if I'm supposed to post this query in another forum. I couldn't find any other link. Are you active on stackoverflow ? Thanks, again for your effort with unpoly.

**Comment by triskweline** [comment]
Hey @deepakmn. We removed IE9 support earlier this year. Since January 2016 IE9 no longer receives security patches from Microsoft, so it's pretty risky to use that browser today.

Our preferred way of dealing with unsupported browsers is to not run JavaScript at all. The user falls back to a classic server-side application. E.g. if we use JavaScript to enhance a `input.date-picker` with a visual date picker component, a legacy browser would just get a vanilla text field.

If you absolutely need to activate JavaScript on unsupported browser, you would do it like so:

```
function activateDatePicker($input) {
  $input.datepickerify({ option: 'value' });
}

up.compiler('input.datepicker',activateDatePicker);

if (!up.browser.isSupported()) {
  $(function() {
    activateDatePicker($('input.datepicker'));
  });
);
```

> Are you active on stackoverflow ?

I'm happy to answer questions on Stackoverflow. You would however need to ping me on Twitter or e-mail (henning dot koch at makandra dot de) so I know about the question.
