### ISSUE TITLE
Unpoly caches by default contrary to the documentation 

### ISSUE THREAD

**Issue by apollo13** [unpoly/unpoly#247]
### Bug description

According to https://unpoly.com/a-up-follow#up-cache and https://unpoly.com/up.request#options.cache unpoly should not cache stuff by default, `With { cache: false } (the default) Unpoly will always make a network request.`

It seems to me that the actual default is `{ cache: 'auto' }`

### Reproduction project

https://glitch.com/edit/#!/heathered-loud-comb

### Steps to reproduce the behavior:

1. Go to reproduction project linked above
2. Open browser debug tools and switch to network tab
3. click "click me" and observe a request being made
4. hit escape
5. click "click me" and observe no request being made

### Expected behavior

Every click should trigger a new server request

### Browser version

 - OS: all
 - Browser: all

**Comment by apollo13** [comment]
I just found that navigation uses different defaults: https://unpoly.com/navigation -- which makes total sense. Maybe the documentation could somehow reflect that (ie https://unpoly.com/a-up-follow#up-cache should say that true is the default?).

**Comment by adam12** [comment]
Would it be clearer if `up-cache` mentioned that the default value is dependent on if it's `navigation` or not (which by default, it is)?

I'd hate to have to add that to each option which is dependent on the navigation setting, since it's mentioned at the top of the page, but perhaps for `up-cache` it's worth the exception. WDYT?

**Comment by apollo13** [comment]
Good question. I mean it is mainly my fault for not reading carefully enough. But `up-cache` links to `options.cache` which says the default is `false` :D 

> Would it be clearer if `up-cache` mentioned that the default value is dependent on if it's `navigation` or not (which by default, it is)?

I guess that would help, but there are more navigation things like scroll, history etc… which have different defaults. But either way for `up-cache` the documentation seems to be particularly missleading since it doesn't even mention `false` which made me even more convinced that this would be the default :)

I have no strong feelings, closing this ticket would probably be fine as well -- sorry for not having better ideas.

**Comment by triskweline** [comment]
I made `[up-navigate]` (or `{ navigate }`) the topmost option in the docs. Its docs now say:

> Setting this to `false` will disable most defaults documented below, causing Unpoly to render a fragment without side-effects like updating history or scroll positions.

Then I documented all stock navigation as defaults for `a[up-follow]`. This is somewhat imprecise since the defaults depend on `[up-navigate]`, which was my original reason to document no defaults at all. However, since `a[up-follow]` navigates by default, most users will get navigation options in most cases. 

I also documented the `false` value for `[up-cache]`.
