### ISSUE TITLE
up-switch ignored when isSupported is false

### ISSUE THREAD

**Issue by adam12** [unpoly/unpoly#29]
I've ran into this a few times, and I'm not sure if it's specific to [my implementation of the server protocol](https://github.com/adam12/roda-unpoly) or just the way it is, but curious if we can work around it somehow.

Every once in a while, `isSupported` is false, due to `up.protocol.initialRequestMethod() === 'get'` being false inside `canPushState`.

When this happens, my use of `up-switch` is ignored, as Unpoly doesn't boot.

I've compared my implementation of the server protocol with the official Rails one, and it looks accurate, so I'm thinking it's more likely somewhere in Unpoly that needs to be tweaked. Perhaps we could have a separate conditional that's used only for view-state, and not related to XHR?

Thanks again for Unpoly - a huge joy to use :)

**Comment by adam12** [comment]
Also, [docs for `isSupported`](https://unpoly.com/up.browser.isSupported) don't seem to match implementation?

AFAIK, it's a chained boolean, and all criteria have to be truthful.

**Comment by triskweline** [comment]
There's a misunderstanding.

When `isSupported` is `false`, Unpoly does not run any code at all. All `up-*` selectors including `up-switch` are no longer active.

Only when `isSupported` is `true`, we offer graceful degredation for selected features that are missing from browser support. The most important being degredation for `history.pushState`.

The `master` branch also has a bug in `isSupported` in that it checks for `pushState` support in the boolean chain. Since we offer graceful degredation for `pushState`, the function should still return true if that feature is unsupported.

This is fixed in the [branch for the next major release](https://github.com/unpoly/unpoly/tree/hk/jquery3-use-native-promise).
