### ISSUE TITLE
Trying to update a <tr> from a fragment with only a <tr> replaces the entire document instead

### ISSUE THREAD

**Issue by alexandergitter** [unpoly/unpoly#360]
### Bug description

I'm trying to replace a table row element `<tr>` with an different `<tr>` from a server response.
When the server returns a fragment with only a `<tr>` element, unpoly switches out the entire document instead of just updating the table row.

### Reproduction project

https://jsfiddle.net/w4po9gsj/

### Steps to reproduce the behavior:

1. Go to reproduction project linked above
2. Click on 'Replace span' to see the `<span>` getting updated correctly
3. Click on 'Replace tr'. Notice how in that case the entire body gets replaced with the content of the table cell.

### Expected behavior

unpoly replaces only the targeted `<tr>` element.

### Browser version

 - OS: Linux
 - Browser: Latest Chromium, Firefox

**Comment by adam12** [comment]
Thank you for providing a fiddle as it did help illustrate your issue. This came up just a few days ago in [Discussions](https://github.com/unpoly/unpoly/discussions/357) as well.

I doubt Unpoly will be able to make this work, as I believe it's a restriction of the browser's parser. IIRC, Unpoly will parse the fragment (using the browser) then extract from the fragment the tree it needs. A `<tr>` without a parent `<table>` isn't valid, and the browser won't parse it to be valid. This prevents Unpoly from capturing what it needs from it.

You can return a `<tr>` tag, but ensure it's valid HTML by being nested in a `<table>`.

```
<input type="hidden" name="html" value="<table><tr id='tr-target'><td>new table content</td></tr></table>">
```

You can see this for yourself in the console:

```javascript
parser = new DOMParser()

// Invalid
parser.parseFromString("<tr><td>Foo</td></tr>", "text/html")

// Valid
parser.parseFromString("<table><tr><td>Foo</td></tr></table>", "text/html")
```

![image](https://user-images.githubusercontent.com/17083/156429901-f5625f0e-bd3b-4272-a6f0-f553d33f1778.png)

I'm going to close this as I think it's unfixable from our side, but LMK if you don't believe it is and if so, how it might be.

**Comment by triskweline** [comment]
Now that we're dropping IE11 support there may be a way to parse incomplete HTML fragments by using `<template>` elements:

![Screenshot from 2022-03-04 22-10-53](https://user-images.githubusercontent.com/89953/156842180-1e01e6dd-5563-431d-9fdc-95eb1d9ad121.png)

We would need to benchmark this vs. `DOMParser` since parsing HTML is the single most expensive task we do when rendering.

Also we would need to keep using `DOMParser` if we see a `<body ...>` or `<html ...>` element in the HTML. `<template>` elements can only parse fragments, not entire documents.

Reopening in case someone wants to tackle this.

**Comment by adam12** [comment]
I'd need to confirm this by hand, but I just used `tr#some_id` as a selector in an Unpoly 3 project and I believe it worked as expected. So this might be resolved.

**Comment by triskweline** [comment]
> Also we would need to keep using DOMParser if we see a <body ...> or <html ...> element in the HTML. <template> elements can only parse fragments, not entire documents.

This is a terrible idea (of mine). There are many, many edge cases how elements parsed using `DOMParser()` behave differently from parsing elements with methods `template.content.cloneNode()` because the results belong to different `Document` instances. Unpoly already handles the fallout of `DOMParser` in regard to script elements, noscript elements and custom elements. This code is delicate enough already, we cannot have two code paths here.

**Comment by triskweline** [comment]
> This is a terrible idea (of mine). There are many, many edge cases how elements parsed using DOMParser() behave differently from parsing elements with methods template.content.cloneNode() because the results belong to different Document instances. Unpoly already handles the fallout of DOMParser in regard to script elements, noscript elements and custom elements. This code is delicate enough already, we cannot have two code paths here.

Closing this issue. There is no idea and we shouldn't introduce more code paths to cover the edge case of updating single `<tr>` elements.

**The workaround is to always wrap your `<tr>` in a `<table>`, even if you're responding with a single row.**
