### ISSUE TITLE
up-navigate=false seems to be broken for layers

### ISSUE THREAD

**Issue by j4mie** [unpoly/unpoly#368]
### Bug description

I am trying to open a modal, but disable navigation (so the URL in the location bar remains the same as it was for the original page in the bottom layer)

This works fine and opens the layer successfully, but (obviously) navigation happens:

```html
<a href="overlay.html" up-layer="new">open layer</a>
```

When I add the `up-navigate="false"` attribute:

```html
<a href="overlay.html" up-navigate="false" up-layer="new">open layer</a>
```

I get a traceback in the console:

<img width="540" alt="image" src="https://user-images.githubusercontent.com/6988/159902868-cfa99079-fd82-4f8f-a93f-99269d5e5a74.png">

### Reproduction project

https://glitch.com/edit/#!/broken-nickel-bolt

Preview here: https://broken-nickel-bolt.glitch.me/

### Steps to reproduce the behavior:

1. Go to reproduction project linked above
2. Click "open layer" link
3. See browser dev tools console for error

### Expected behavior

The modal should open, but the URL in the browser's location bar shouldn't change.

### Browser version

 - OS: macOS
 - Browser: Firefox
 - Version: 99.0b4

**Comment by triskweline** [comment]
To open an overlay without location changes, use `[up-history=false]`.

By setting `[up-navigate=false]` you deactivate [many defaults](https://unpoly.com/navigation#navigation-defaults), including falling back to `:main` when no target selector is given. That's why you're seeing the error message.

You could use `[up-navigate=false]` together with an explicit `[up-target]`, but I think `[up-history=false]` is what you want here.

**Comment by j4mie** [comment]
@triskweline thank you for the quick reply. That works perfectly. I wonder if it might be worth linking from the `up-navigate` section of the docs to `up-history` with an explanation similar to what you've written above? I had no idea the latter existed!

Cheers 🙂
