### ISSUE TITLE
Using `up-target` with a selector list fails if one selector from the list is not found

### ISSUE THREAD

**Issue by jiegillet** [unpoly/unpoly#387]
### Bug description

When using `up-target` with a selector list (`up-target=".a, .z"`), if at least one of the elements of the list is not in the page (there is one `class="a"` but there is no `class="z"`), the whole body is replaced.

### Reproduction project

https://glitch.com/edit/#!/ivory-geode-party 

### Steps to reproduce the behavior:

1. Go to reproduction project linked above
2. Click Settings > Go to project page
3. Click on "Replace a", first div is replaced (expected)
4. Click on "Replace a or b", first two divs are replaced (expected)
5. Click on "Replace a or z", the whole body is replaced (unexpected)

### Expected behavior

I would expect the whole body to be replaced only if **none** of the selectors in the list match **anything**.
If one or several elements match at least one selector from the selector list, only those should be replaced.

### Browser version

 - OS: macOS Monterey
 - Browser: Firefox (100.2), Safari (15.4)

**Comment by triskweline** [comment]
Thanks for the report.

This behavior is by design. All selectors must match or Unpoly assumes the server rendered unusable content (e.g. an error page).

In the next version you will be able to [suffix selectors with `:maybe`](https://github.com/unpoly/unpoly/blob/6801da91a02e3a6abb6dee824e5307ea34763ca9/src/unpoly/fragment.js#L1322-L1345) to indicate that they're optional. Until then you can often mark optional elements as [`[up-hungry]`](https://unpoly.com/up-hungry) and remove them from your `[up-target]` selector.
