### ISSUE TITLE
Unpoly latest version (2.6) not support for Safari old version 12.1.2

### ISSUE THREAD

**Issue by hungle-agilityio** [unpoly/unpoly#390]
### Bug description
I'm trying out using Unpoly for Safari old version 12.1.2, but not woking right now. Browser does not understand Optional chaining (?.). It only supports for safari version 13.1 and higher.
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining
Could everyone help check for bug, Thanks!

### Browser version

 - OS: [MacOS Mojave]
 - Browser [Safari]
 - Version [12.1.2]

**Comment by triskweline** [comment]
We only test and support the last 2 major versions of Safari. Safari 12 has a remaining market share of < 0.05% so we don't want to invest the time.

Your particular problem with optional chaining could be fixed by using the [ES5 build](https://unpoly.com/install#legacy-browsers) of Unpoly. Since we don't test for Safari 12 you may or may not discover other issues that you need to fix with transpiling or polyfills.

**Comment by hungle-agilityio** [comment]
> We only test and support the last 2 major versions of Safari. Safari 12 has a remaining market share of < 0.05% so we don't want to invest the time.
> 
> Your particular problem with optional chaining could be fixed by using the [ES5 build](https://unpoly.com/install#legacy-browsers) of Unpoly. Since we don't test for Safari 12 you may or may not discover other issues that you need to fix with transpiling or polyfills.

Thank you for your supported!
