### ISSUE TITLE
AJAX acceleration does not support PUT HTTP method (only sends a POST)

### ISSUE THREAD

**Issue by acnebs** [unpoly/unpoly#51]
As far as I can tell, `up.request(..., {method: 'PUT'})` sends a POST request instead of the desired PUT request, making the distinct handling of PUT/POST in our REST backend useless. 

Is there a reason for this? Am I missing something obvious?

**Comment by adam12** [comment]
Basically, browsers didn't (and might still) not support anything other than GET/POST (not including HEAD and OPTIONS). To work around this, Ruby on Rails started adding a `_method` parameter to all forms that weren't a GET or POST. This was adopted by other libraries and frameworks, and somewhat became the de-facto standard.

Unpoly works in the same way - the actual request is a POST, but with `_method=PUT` as a parameter.

If you're using Rack or something based off it, there is a `Rack::MethodOverride` middleware you can use to enable the `_method` param.

**Comment by acnebs** [comment]
Ah, I didn't realize this was a layover from Rails. But support in browsers for GET/POST is only applicable to HTML **forms**. This is an AJAX request though, so it is presumably using XMLHttpRequest under the hood, which *does* support the PUT method.

Additionally, jQuery's `$.ajax()` also supports the PUT method, and since Unpoly is built on top of jQuery, it seems sensible to include the method in its vanilla form, rather than being wrapped in a POST.

**Comment by adam12** [comment]
Yes , it was form specific. The original premise was that without Javascript, people still expected forms to submit correctly (ala, the original `button_to` helper in Rails).

Since Unpoly wouldn't be used without Javascript enabled, I agree that Unpoly should use the native method where possible.

But looking at the source code, it looks like this is already the case, except Unpoly makes the decision to wrap non-GET/POST methods into a POST, as you're seeing. You just need to tell Unpoly not to wrap them in a POS.

Spitballing here, but you could try this:

```javascript
up.proxy.config.wrapMethods = []
```

**Comment by acnebs** [comment]
Ah, I looked into the source enough to realize that methods were being wrapped, but not closely enough to see that solution.

It worked perfectly, thank you @adam12!

**Comment by triskweline** [comment]
Also note that while many browsers now support verbs like `PUT`, `PATCH`, they [handle redirect responses  in an unexpected way](https://makandracards.com/makandra/38347-ajax-requests-with-patch-or-delete-method-will-not-redirect-with-get).

That's another reason why many frameworks like Rails, Symfony and Express offer a way to wrap the verb in a `_method` param.
