### ISSUE TITLE
Wrong cursor position on up-autosubmit form with field type="number"

### ISSUE THREAD

**Issue by davisums** [unpoly/unpoly#525]
### Bug description

I have a form with up-autosubmit attribute, and one of the fields has a type="number". The field is auto-updated correctly, but the cursor appears at the start of the field after each update

![CleanShot 2023-09-03 at 22 39 26](https://github.com/unpoly/unpoly/assets/58007085/1f118c64-2838-48b6-9de1-a51538aab3a3)

### Steps to reproduce the behavior:

This is the part of my form that's causing issues:

```
<form id="ai-model-base-form"
      class=""
      up-autosubmit
      up-watch-delay="1000"
      action="{% url 'webapp:ai_models_update' ai_model.id %}"
      up-submit
      up-target="#ai-model-base-form"
      method="POST">

<input type="number" name="steps_per_image" value="12453" required="" id="id_steps_per_image">
```

### Expected behavior

Unpoly remembers the cursor position inside the form

### Browser version

 - OS: Mac OS
 - Browser Chrome
 - Version 116.0.5845.140

### Additional context

This only seems to happen for fields of type="number". I haven't tested if it happens without the up-autosubmit as well.

**Comment by triskweline** [comment]
Unpoly preserves the `{ selectionStart, selectionEnd, scrollLeft, scrollTop }` properties.

Apparently these properties were [intentionally omitted from number inputs](https://github.com/whatwg/html/issues/2358) because a browser could choose to show a non-textual input method, like a number dial.

Closing this because nothing Unpoly can do.

As a workaround, consider using a `<input type="text" inputmode="numeric" pattern="[0-9]">` instead.
