### ISSUE TITLE
Appending content doesn't work if one of the targets is missing

### ISSUE THREAD

**Issue by bummzack** [unpoly/unpoly#55]
Maybe more of a question than an issue…

Using `unpoly@0.53.3` and the following Markup:

```html
<div class="news-list">
  <!-- List of news Entries, each one is a <section> -->
</div>
<a href="news?start=3" 
   class="button button--load-more" 
   up-target=".news-list:after, .button--load-more">
  Load more
</a>
```

At the end of the list, the load-more button is omitted in the server generated output, eg. the last "page" of the news list looks like this:

```html
<div class="news-list">
  <!-- Last news Entries, each one is a <section> -->
</div>
<!-- Load more button omitted -->
```

Appending new items works as long as the "load-more" button isn't omitted. If the button is missing, the "body" is completely replaced instead. Is there a way to set "soft" targets, so if they are missing from the response they get removed instead?

The workaround I'm currently using is returning something like this on the last page:

```html
<div class="news-list">
  <!-- Last news Entries, each one is a <section> -->
</div>
<span class="button--load-more"></span>
```

**Comment by triskweline** [comment]
All targets must be present in both current page and response for a partial replacement to succeed. If any selector is missing in either, Unpoly will assume the page is in an unexpected state. It will then go through the selectors in [`up.dom.config.fallbacks`](https://unpoly.com/up.dom.config) to find an alternative match. 

The default for `up.dom.config.fallbacks` is `['body']` which is why you're seeing the whole page replaced when `.button--load-more` is missing.

> The workaround I'm currently using is returning something like this on the last page:

That's how I would implement this. You can hide unwanted margins around the element with a CSS rule like `.button--load-more:empty { display: none }`.

> Is there a way to set "soft" targets, so if they are missing from the response they get removed instead?

Not currently. I think it's a good idea for a future feature, although we would need to think hard about the expected behavior when an optional target is missing from the response. I think someone could expect three different things:

- Remove the unmatched element from the current page (your expectation)
- Don't change the unmatched element (this is how [`[up-hungry]`](https://unpoly.com/up-hungry) works)
- Empty the content of the unmatched element

One possible issue with removing the unmatched element is that once it's removed, it can no longer match in a future replacement. In your example, if another link wants to go back to page 1 by replacing `.news-list, .button--load-more:optional`, we would never get that button back.

**Comment by bummzack** [comment]
Thanks a lot for the detailed explanation! I'm fine with the workaround.
