### ISSUE TITLE
Uncaught TypeError: Cannot read property 'offsetWidth' of null

### ISSUE THREAD

**Issue by ijcd** [unpoly/unpoly#58]
I am having an odd interaction between unpoly and uikit. The version of uikit does not seem to matter, but something between 0.37.0 and 0.50.0 of unpoly.js is causing the following to be triggered.

This is happening during a call to up.extract()

What might have changed to cause this? 

With some version combinations, things keep working, but I get the message. WIth others, it just stops working altogether. I'm thinking there is a race condition between handlers in uikit.js and unpoly.js, perhaps?

Any suggestions on where to look first? What kind of information could I supply to help narrow this down?

```
uikit.js:6682 Uncaught TypeError: Cannot read property 'offsetWidth' of null
    at UIkitComponent.write (uikit.js:6682)
    at uikit.js:2940
    at runTasks (uikit.js:1909)
    at Object.flush (uikit.js:1887)
write @ uikit.js:6682
(anonymous) @ uikit.js:2940
runTasks @ uikit.js:1909
flush @ uikit.js:1887
requestAnimationFrame (async)
scheduleFlush @ uikit.js:1902
read @ uikit.js:1870
(anonymous) @ uikit.js:2924
UIkit._callUpdate @ uikit.js:2913
update @ uikit.js:2814
UIkit.update @ uikit.js:2786
applyMutation @ uikit.js:2668
observe.childList @ uikit.js:2649
childList (async)
(anonymous) @ jquery.js:5930
domManip @ jquery.js:5743
after @ jquery.js:5928
jQuery.fn.(anonymous function) @ jquery.js:6036
detachWith @ unpoly.js:2020
transferKeepableElements @ unpoly.js:7121
swapElements @ unpoly.js:7079
(anonymous) @ unpoly.js:6981
group @ unpoly.js:4816
(anonymous) @ unpoly.js:6978
rejectOnError @ unpoly.js:2100
(anonymous) @ unpoly.js:6964
group @ unpoly.js:4816
extract @ unpoly.js:6954
applyPresto @ app.js:193
(anonymous) @ app.js:233
(anonymous) @ app.js:232
(anonymous) @ phoenix.js:619
trigger @ phoenix.js:618
(anonymous) @ phoenix.js:1042
(anonymous) @ phoenix.js:1041
decode @ phoenix.js:671
onConnMessage @ phoenix.js:1027
conn.onmessage @ phoenix.js:830
```

**Comment by triskweline** [comment]
I'm not familiar with UIKit, so I can only guess:

It looks like UIKit is using [MutationObserver](https://developer.mozilla.org/de/docs/Web/API/MutationObserver) to run JavaScript whenever an element enters or leaves the DOM. Unpoly replacements manipulate the DOM, so UIKit JavaScript will run when Unpoly changes anything.

The stack trace above shows that you're using the [`up-keep`](https://unpoly.com/up-keep) attribute. To process `up-keep` elements, Unpoly needs to temporarily detach keepable elements from the DOM. It looks like UIKit runs its JavaScript on detached elements, but crashes because it cannot find the element's scrolling viewport (to measure scroll positions or something).

The major change in Unpoly 0.50+ is that we're now using native promises instead of jQuery deferreds. This means that async code now runs in the [next microtask instead of the next task](https://jakearchibald.com/2015/tasks-microtasks-queues-and-schedules/). This may have changed the order in which async code in Unpoly and UIKit is scheduled.

You could try to make your app work without `[up-keep]`, but it doesn't change the underlying issue that UIKit seems to assume that it is the only code working with the DOM.

**Comment by ijcd** [comment]
Thank you, this information will be helpful.
