### ISSUE TITLE
JS error when using up-submit: Uncaught up.Error: up.on(): The "up:click" callback function executeEmitAttr; EDIT: Putting the script in the end of body breaks the js

### ISSUE THREAD

**Issue by sawirricardo** [unpoly/unpoly#587]
### Bug description

![image](https://github.com/unpoly/unpoly/assets/37329575/b4c860e8-598f-4430-9e58-9452abae8671)

### Reproduction project

[unpoly-issue-upclick.zip](https://github.com/unpoly/unpoly/files/14254815/unpoly-issue-upclick.zip)

### Steps to reproduce the behavior:

1. Download the zip
2. `./unpoly-issue-upclick`
3. open http://127.0.0.1:8000
4. try click the button, and see the error in the console log

### Expected behavior

no up error

### Browser version

 - OS: Mac
 - Browser Chrome
 - Version 121.0.6167.160 (Official Build) (arm64)

### Additional context
If you wonder about the code, you can inspect the main.go (backend) and the main.templ (frontend)

**Comment by sawirricardo** [comment]
### New finding
It seems the issue is because the unpoly script is put in the <body> instead of <head> 
I think maybe it's worth mentioning that the script **must** be put in the <head> instead of the end of <body>

**Comment by triskweline** [comment]
`unpoly.js` must never be included more than once. Here is what happens:

- The initial page is loaded. The browser sees the script for `unpoly.js` `<body>`, loaded and run.
- You click on the link. Unpoly loads the link destination.
- Because Unpoly cannot find a [main element](https://unpoly.com/up-main) it swaps the `<body>` element.
- The browser sees the script for `unpoly.js` `<body>` and runs it a second time. This throws an error.

Here are three ways to fix this (you only need one):

1. Move your scripts into the `<head>` and use the `<script defer>` attribute. [This is superior to putting your script at the end of the body](https://makandracards.com/makandra/504104-you-should-probably-load-your-javascript-with-script-defer).
2. Wrap your content into a `<main>` or `[up-main]` element so Unpoly does not need to swap the `<body>`.
3. Configure [`up.fragment.config.runScripts = false`](https://unpoly.com/up.fragment.config#config.runScripts)
