### ISSUE TITLE
Fragment load interfering with Trix Editor webcomponent operation

### ISSUE THREAD

**Issue by onomated** [unpoly/unpoly#61]
Started integrating [Trix editor](https://trix-editor.org/) ([GitHub](https://github.com/basecamp/trix)) in my project and find that its functionality fails to initialize when its containing fragment is loaded with Unpoly.  Submitted an issue (https://github.com/basecamp/trix/issues/510) with the Trix team which we narrowed down to some unpoly interaction breaking its functionality.  This codepen illustrates this:
https://codepen.io/onomated/project/editor/ARnQvn

A full page refresh and a simple JQuery ajax load of a fragment containing the `trix-editor` tag work as expected.  However, when loaded with an unpoly link, the `trix-editor` fails to initialize.

**Comment by triskweline** [comment]
Unpoly uses [DOMParser](https://developer.mozilla.org/docs/Web/API/DOMParser) to parse a new fragment, so we can run selectors on it. I'm assuming that `DOMParser` runs on an anonymous `document` that doesn't have Trix' web component registration.

We probably need to call `document.importNode()` on elements before we insert them into the current page. Since this copies the element, we should investigate the performance impact of that.

**Comment by triskweline** [comment]
Custom element activation works with the current Unpoly version. There is no need to call `document.importNode()`.

I don't know what's preventing `<trix-editor>` from initializing.

**Comment by triskweline** [comment]
Trix is using the deprecated version 0 of the custom elements spec (`document.registerElement`). V0 components will not be upgraded in elements parsed by [`DOMParser`](https://developer.mozilla.org/docs/Web/API/DOMParser) unless the element is first copied using the (expensive) `document.importNode()`.

Custom elements defined with the version 1 of the spec (`customElements.define`) work with `DOMParser` results and don't require expensive calls to `document.importNode()`.

Test results are in this Gist:
https://gist.github.com/triskweline/0d4561d0d8f41997559cd22139be81cc

I don't want to change Unpoly to use `document.importNode()` and make fragment updates slower for everyone, for the off-chance that someone might need a V0 component.

You might want to work with the Trix maintainers to upgrade their code to the V1 spec.

As a workaround, you could send a `<div class="trix-editor">` (instead of `<trix-editor>`) over the wire, and create the `<trix-editor>` component from an Unpoly compiler:

```
up.compiler('.trix-editor', function($element) {
  $element.innerHTML = '<trix-editor></trix-editor>'
})
```

**Comment by onomated** [comment]
Thanks @triskweline.  I'll forward to Trix maintainers

**Comment by javan** [comment]
That's unfortunate. You could use `document.implementation.createHTMLDocument('')` instead of `DOMParser`, which works as expected (without `document.importNode()`ing). Curious how it compares performance wise.

Example: https://gist.github.com/javan/edb0445527af29457871896469418dab

**Comment by triskweline** [comment]
Thanks for looking into this @javan .

Peformance-wise there is little difference. These stats come from parsing 13K of HTML without custom elements, 5000 times, with 10% outliers removed, in Chrome on Linux:

```
Experiment PlainDOMParser: {minimum: 8.399999998800922, maximum: 62.600000001111766, median: 10.500000000320142, total: 6087.099999964266, setSize: 490}
Experiment CreateHTMLDocument: {minimum: 8.400000002438901, maximum: 49.89999999816064, median: 10.100000003149034, total: 6024.900000069465, setSize: 490}
```

One disadvantage of solutions that use `innerHTML` is that they will immediately upgrade all custom elements in the given HTML, calling the `createdCallback()` properties in the process. In contrast, DOMParser parses elements in an anonymous document without scripting capabilities.

In Unpoly's standard use case we will parse full HTML documents, but then only select a few fragments that we insert in the current DOM. It's like Turbolinks in a way, but users will usually target page fragments instead of entire screens. With an `innerHTML` solution we would run constructor functions for elements that we are going to discard.

**Comment by onomated** [comment]
Going with the workaround for now.  Thanks @triskweline and @javan for creating awesome components that allow small dev shops look like rockstars!
🎉

**Comment by javan** [comment]
> One disadvantage of solutions that use `innerHTML` is that they will immediately upgrade all custom elements in the given HTML, calling the `createdCallback()` properties in the process.  In contrast, `DOMParser` parses elements in an anonymous document without scripting capabilities.

Does that really matter?

Alternate idea: Insert HTML instead of nodes.
```diff
     function show(selector, element) {
       if (!element) {
         element = document.createElement('i')
         element.innerHTML = 'no element found'
       }
-      document.querySelector(selector).appendChild(element);
+      document.querySelector(selector).insertAdjacentHTML('beforeend', element.outerHTML);
     }
```
