### ISSUE TITLE
up-validate replaces all instances of target instead of a single target wrapping the field being changed

### ISSUE THREAD

**Issue by sturatcliffe** [unpoly/unpoly#90]
Maybe I'm misunderstanding the docs, but I *think* that if I wrap a form input with an element with the `up-target` attribute, only that form input should be replaced when validating the form using `up-validate`.

However, this isn't the case unless I explicitly tell the `up-validate` attribute to replace the `[up-fieldset]` target like so:

```
<div class="form-group" up-fieldset>
    <label>E-mail</label>
    <input class="form-control" name="email" up-validate="[up-fieldset]" />
    <span class="error"></span>
</div>
```

If I just use the `up-validate` attribute with no explicit target like so:

```
<div class="form-group" up-fieldset>
    <label>E-mail</label>
    <input class="form-control" name="email" up-validate />
    <span class="error"></span>
</div>
```

The whole form is replaced showing errors for other fields which haven't been interacted with yet. Is this the intended behaviour or a bug?

EDIT:

Just realised it actually replaces *all* instances of the target you specify as well. So unless you use unique ID's on each form group, `up-validate` will show validation messages for all form fields - my understanding was it was supposed to only replace a section around the input that triggers the validation call?

Cheers!

**Comment by triskweline** [comment]
The `[up-fieldset]` attribute was removed in 0.60.0 and I forgot to update the docs. Since Unpoly did not find a label/input group within the form to update, it defaulted to updating the entire form.

I re-introduced the `[up-fieldset]` attribute in 0.60.3. You may also define your own selectors for this in `up.form.config.validateTargets`.

> Just realised it actually replaces all instances of the target you specify as well. So unless you use unique ID's on each form group, up-validate will show validation messages for all form fields - my understanding was it was supposed to only replace a section around the input that triggers the validation call?

Your fieldsets don't need a unique ID if the contained input has a unique `id`, `name` or `aria-label` attribute.

**Comment by sturatcliffe** [comment]
Thanks @triskweline - working nicely now!

However, I have another question on this which I don't think is fair to raise as an issue so I hope you don't mind my asking here!

Nearly all of my forms end up having the same unpoly data attributes adding to them, i.e. `up-target` and `up-history`. I also always add the `up-fieldset` attribute to divs wrapping my inputs, as well as the `up-validate` attribute to inputs within. Rather than keep remembering to add these, or writing server-side helpers to render them on the server, I was trying to use a few `up.macro`'s to avoid the duplication, but then when my forms are submitted I get problems with unpoly not finding the targets to replace as they are obviously not being added until *after* the replacement code is run. 

Is there any way I can force my macros to run before unpoly tries to replace the fragments returned from the server? Or should I be trying to automate the rendering of these attributes on the server instead?

Thanks!

**Comment by triskweline** [comment]
> Is there any way I can force my macros to run before unpoly tries to replace the fragments returned from the server?

I'm afraid that's not currently possible, and unlikely to be added.

> I was trying to use a few up.macro's to avoid the duplication, but then when my forms are submitted I get problems with unpoly not finding the targets to replace as they are obviously not being added until after the replacement code is run.

I haven't yet encountered a case where the side effects of a macro were required to identify an element. Except maybe with fieldsets, for which we are using a different solution (see below).

> Or should I be trying to automate the rendering of these attributes on the server instead?

This is mostly what we do. With our web framework (Rails) the developer already uses server-side helpers to render links and forms. So we configure those helpers to set any default Unpoly attributes we want.

In some cases we can also configure Unpoly with better defaults.

E.g. when using Bootstrap you are grouping label/input pairs into a `<div class="form-group">...</div>` for styling reasons. So instead of explicitely setting `[up-fieldset]` we tell Unpoly that `.form-group` matches a fieldset in our app:

    up.form.config.validateTargets.push('.form-group')

In the same fashion you can push a default target for all your links and forms into `up.fragment.config.fallbacks`. You still need to mark up followable links/forms with an empty `[up-follow]` or `[up-target]`, or use a `up.macro()` to do it for you.

**Comment by sturatcliffe** [comment]
Thanks for coming back to me @triskweline it's really helpful. I'm using ASP.NET Core and started playing around with some tag helpers to automate the addition of default unpoly attributes, and it's working well and easier than I thought. Thanks again!
